apiVersion: v1
kind: Secret
metadata:
  name: sanction-monitor-secrets
  namespace: sanction-monitor
type: Opaque
stringData:
  ANTHROPIC_API_KEY: "REPLACE_ME" # We are not checking this in...

  # Sanctions DB credentials
  SANCTIONS_DB_USER: "sanctions_user"
  SANCTIONS_DB_PASSWORD: "sanctions_pass"
  SANCTIONS_DB_NAME: "sanctions"
  SANCTIONS_DATABASE_URL: "postgres://sanctions_user:sanctions_pass@sanctions-db:5432/sanctions"

  # Dashboard DB credentials
  DASHBOARD_DB_USER: "dashboard_user"
  DASHBOARD_DB_PASSWORD: "dashboard_pass"
  DASHBOARD_DB_NAME: "dashboard"
  DASHBOARD_DATABASE_URL: "postgresql://dashboard_user:dashboard_pass@dashboard-db:5432/dashboard"
